version: '3.8'

services:
  backend:
    build:
      context: ./dist-backend
      dockerfile: Dockerfile
    container_name: dist-backend
    ports:
      - "3000:3000"
    env_file:
      - ./dist-backend/.env
    volumes:
      - ./dist-backend/storage:/app/storage
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dist-db
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Root.12345
    ports:
      - "1433:1433"
    volumes: 
      - db_data:/var/opt/mssql
      - ./db-init:/db-init


  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dist-db-initializer
    depends_on:
      - db
    volumes:
      - ./db-init:/db-init
    environment:
      ACCEPT_EULA: Y
    command: >
      bash -c '
      echo "Esperando a que SQL Server inicie (20s)..."
      sleep 20
      echo "Ejecutando script initSQL.sql..."
      /opt/mssql-tools18/bin/sqlcmd -S db -U SA -P "Root.12345" -C -i /db-init/initSQL.sql
      echo "Ejecución finalizada."
      '

volumes:
  db_data: {}